<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <TargetPlatformVersion>10.0</TargetPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SoundWatcher</AssemblyName>
    <RootNamespace>SoundWatcher</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- Single-file publish configuration -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfContained>true</IncludeNativeLibrariesForSelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\AppIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="4.3.3.952" />
  </ItemGroup>

</Project>
